### PR TITLE
Multi-platform support

### PR DESCRIPTION
**Pull request by stachu540**
Now script supporting as multi-platform.
Tested by myself, and works good.

Added some session key exists (watch `hirez.smite('platform').session.test()` or `hirez.paladins('platform').session.test()`). He will check if session key is exists on environment system. You can remove it, on your wishes.

### CODE REVIEW

**Comment by messyfresh** [comment]
Wow! Lots of great improvements in here! I will review all of it this Friday (I work ~60 hours a week) since this will be a Major semver increment, since it doesn't look backwards compatible due to the introduction of ('platform') in each call.  (I could be mistaken, I'm pretty tired)

**Comment by stachu540** [comment]
It is nothing big deal. Adding some changes, coppule test's on the own Discord bot (Repo is private - still in beta). And there you go. Supporting multi-platform. Now you can add some more methods on the classes like my Java repository: https://github.com/stachu540/HiRezAPI - 3 Days work on my project and we got good API wrapper.

**Comment by messyfresh** [comment]
Works great on my end!  Thanks for the contribution. I need to start a list of contributors.

**Comment by stachu540** [comment]
Also, don't forget a bumping this version before release it.

**Comment by messyfresh** [comment]
Done and done! v2.0.0 https://www.npmjs.com/package/hirez.js

**Pull request merged**
