### PR TITLE
Added support for RealmAPI, Close #12

### LINKED ISSUE #12: [Feature] Realm Royale Endpoint Support
- Add supports for Realm Royale endpoints.

### PR DESCRIPTION
**Pull request by WeiRui-Wang**
Added supports for [RealmAPI](https://github.com/apugh/realm-api-docs/wiki).
+ Added support for RealmAPI
+ Updated manual for generic session creation and skeleton Realm API usage
+ Closed #12

Acknowledgements:
RealmAPI related modules was adapted from awesome ground work made by @messyfresh @stachu540 @LongLiveCHIEF @iamtraction

### CODE REVIEW

**Comment by WeiRui-Wang** [comment]
As mentioned from #11, during feature testing, Smite and Paladins endpoints appears to be updated from HiRez side to enforce HTTPS. Feel free to address the issue in a new patch PR. Changes should be straightforward by simply adding 's' to all the main URL.

**Review by messyfresh — APPROVED** [review]
Looks great!

**Review by messyfresh — APPROVED** [review]

**Comment by WeiRui-Wang** [comment]
Awesome! Feel free to push the update to npm also. Thanks! @messyfresh

**Comment by messyfresh** [comment]
Done! NPM is now updated with version 2.0.1 to include the RealmAPI changes.

**Comment by WeiRui-Wang** [comment]
> Done! NPM is now updated with version 2.0.1 to include the RealmAPI changes.

Thanks!

**Pull request merged**
